### ISSUE TITLE
Github pages not deploying.

### ISSUE THREAD

**Issue by spiccoli** [spiccoli/apiCrudWebpage#1]
I am encountering an issue with hosting this particular project on GitHub Pages. It appears that I am unable to host my project due to PHP-related limitations.

**Comment by spiccoli** [comment]
I am encountering an issue with hosting this particular project on GitHub Pages. It appears that I am unable to host my project due to PHP-related limitations.

**Comment by camrionnvmff** [comment]
GitHub Pages does not support PHP as it can only host static websites. If you need to host dynamic websites containing PHP, we recommend that you choose other hosting services. You can consider using free PHP hosting services such as 000webhost, InfinityFree, or Heroku. If you need Php environment deployment, you can consider using the Servbay tool, which comes with built-in HTTPS and SSL.
